apiVersion: apps/v1
kind: Deployment
metadata:
  name: story
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: michaelbab/ story:latest